// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playlist4issues.proto

package com.spotify.playlist4.proto;

public final class Playlist4Issues {
  private Playlist4Issues() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientIssueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.spotify.proto.ClientIssue.Level level = 1;
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
     */
    com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level getLevel();

    // optional .com.spotify.proto.ClientIssue.Code code = 2;
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
     */
    com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code getCode();

    // optional int32 repeatCount = 3;
    /**
     * <code>optional int32 repeatCount = 3;</code>
     */
    boolean hasRepeatCount();
    /**
     * <code>optional int32 repeatCount = 3;</code>
     */
    int getRepeatCount();
  }
  /**
   * Protobuf type {@code com.spotify.proto.ClientIssue}
   */
  public static final class ClientIssue extends
      com.google.protobuf.GeneratedMessage
      implements ClientIssueOrBuilder {
    // Use ClientIssue.newBuilder() to construct.
    private ClientIssue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientIssue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientIssue defaultInstance;
    public static ClientIssue getDefaultInstance() {
      return defaultInstance;
    }

    public ClientIssue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientIssue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level value = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                level_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code value = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                code_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              repeatCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientIssue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientIssue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.class, com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientIssue> PARSER =
        new com.google.protobuf.AbstractParser<ClientIssue>() {
      public ClientIssue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientIssue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientIssue> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.spotify.proto.ClientIssue.Level}
     */
    public enum Level
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEVEL_UNKNOWN = 0;</code>
       */
      LEVEL_UNKNOWN(0, 0),
      /**
       * <code>LEVEL_DEBUG = 1;</code>
       */
      LEVEL_DEBUG(1, 1),
      /**
       * <code>LEVEL_INFO = 2;</code>
       */
      LEVEL_INFO(2, 2),
      /**
       * <code>LEVEL_NOTICE = 3;</code>
       */
      LEVEL_NOTICE(3, 3),
      /**
       * <code>LEVEL_WARNING = 4;</code>
       */
      LEVEL_WARNING(4, 4),
      /**
       * <code>LEVEL_ERROR = 5;</code>
       */
      LEVEL_ERROR(5, 5),
      ;

      /**
       * <code>LEVEL_UNKNOWN = 0;</code>
       */
      public static final int LEVEL_UNKNOWN_VALUE = 0;
      /**
       * <code>LEVEL_DEBUG = 1;</code>
       */
      public static final int LEVEL_DEBUG_VALUE = 1;
      /**
       * <code>LEVEL_INFO = 2;</code>
       */
      public static final int LEVEL_INFO_VALUE = 2;
      /**
       * <code>LEVEL_NOTICE = 3;</code>
       */
      public static final int LEVEL_NOTICE_VALUE = 3;
      /**
       * <code>LEVEL_WARNING = 4;</code>
       */
      public static final int LEVEL_WARNING_VALUE = 4;
      /**
       * <code>LEVEL_ERROR = 5;</code>
       */
      public static final int LEVEL_ERROR_VALUE = 5;


      public final int getNumber() { return value; }

      public static Level valueOf(int value) {
        switch (value) {
          case 0: return LEVEL_UNKNOWN;
          case 1: return LEVEL_DEBUG;
          case 2: return LEVEL_INFO;
          case 3: return LEVEL_NOTICE;
          case 4: return LEVEL_WARNING;
          case 5: return LEVEL_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Level>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Level>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Level>() {
              public Level findValueByNumber(int number) {
                return Level.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.getDescriptor().getEnumTypes().get(0);
      }

      private static final Level[] VALUES = values();

      public static Level valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Level(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.spotify.proto.ClientIssue.Level)
    }

    /**
     * Protobuf enum {@code com.spotify.proto.ClientIssue.Code}
     */
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CODE_UNKNOWN = 0;</code>
       */
      CODE_UNKNOWN(0, 0),
      /**
       * <code>CODE_INDEX_OUT_OF_BOUNDS = 1;</code>
       */
      CODE_INDEX_OUT_OF_BOUNDS(1, 1),
      /**
       * <code>CODE_VERSION_MISMATCH = 2;</code>
       */
      CODE_VERSION_MISMATCH(2, 2),
      /**
       * <code>CODE_CACHED_CHANGE = 3;</code>
       */
      CODE_CACHED_CHANGE(3, 3),
      /**
       * <code>CODE_OFFLINE_CHANGE = 4;</code>
       */
      CODE_OFFLINE_CHANGE(4, 4),
      /**
       * <code>CODE_CONCURRENT_CHANGE = 5;</code>
       */
      CODE_CONCURRENT_CHANGE(5, 5),
      ;

      /**
       * <code>CODE_UNKNOWN = 0;</code>
       */
      public static final int CODE_UNKNOWN_VALUE = 0;
      /**
       * <code>CODE_INDEX_OUT_OF_BOUNDS = 1;</code>
       */
      public static final int CODE_INDEX_OUT_OF_BOUNDS_VALUE = 1;
      /**
       * <code>CODE_VERSION_MISMATCH = 2;</code>
       */
      public static final int CODE_VERSION_MISMATCH_VALUE = 2;
      /**
       * <code>CODE_CACHED_CHANGE = 3;</code>
       */
      public static final int CODE_CACHED_CHANGE_VALUE = 3;
      /**
       * <code>CODE_OFFLINE_CHANGE = 4;</code>
       */
      public static final int CODE_OFFLINE_CHANGE_VALUE = 4;
      /**
       * <code>CODE_CONCURRENT_CHANGE = 5;</code>
       */
      public static final int CODE_CONCURRENT_CHANGE_VALUE = 5;


      public final int getNumber() { return value; }

      public static Code valueOf(int value) {
        switch (value) {
          case 0: return CODE_UNKNOWN;
          case 1: return CODE_INDEX_OUT_OF_BOUNDS;
          case 2: return CODE_VERSION_MISMATCH;
          case 3: return CODE_CACHED_CHANGE;
          case 4: return CODE_OFFLINE_CHANGE;
          case 5: return CODE_CONCURRENT_CHANGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.getDescriptor().getEnumTypes().get(1);
      }

      private static final Code[] VALUES = values();

      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Code(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.spotify.proto.ClientIssue.Code)
    }

    private int bitField0_;
    // optional .com.spotify.proto.ClientIssue.Level level = 1;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level level_;
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
     */
    public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level getLevel() {
      return level_;
    }

    // optional .com.spotify.proto.ClientIssue.Code code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code code_;
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
     */
    public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code getCode() {
      return code_;
    }

    // optional int32 repeatCount = 3;
    public static final int REPEATCOUNT_FIELD_NUMBER = 3;
    private int repeatCount_;
    /**
     * <code>optional int32 repeatCount = 3;</code>
     */
    public boolean hasRepeatCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 repeatCount = 3;</code>
     */
    public int getRepeatCount() {
      return repeatCount_;
    }

    private void initFields() {
      level_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level.LEVEL_UNKNOWN;
      code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code.CODE_UNKNOWN;
      repeatCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, level_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, code_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, repeatCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, level_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, repeatCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spotify.playlist4.proto.Playlist4Issues.ClientIssue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.spotify.proto.ClientIssue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.spotify.playlist4.proto.Playlist4Issues.ClientIssueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientIssue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientIssue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.class, com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Builder.class);
      }

      // Construct using com.com.spotify.proto.Playlist4Issues.ClientIssue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level.LEVEL_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code.CODE_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        repeatCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientIssue_descriptor;
      }

      public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue getDefaultInstanceForType() {
        return com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.getDefaultInstance();
      }

      public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue build() {
        com.spotify.playlist4.proto.Playlist4Issues.ClientIssue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue buildPartial() {
        com.spotify.playlist4.proto.Playlist4Issues.ClientIssue result = new com.spotify.playlist4.proto.Playlist4Issues.ClientIssue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.repeatCount_ = repeatCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spotify.playlist4.proto.Playlist4Issues.ClientIssue) {
          return mergeFrom((com.spotify.playlist4.proto.Playlist4Issues.ClientIssue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.spotify.playlist4.proto.Playlist4Issues.ClientIssue other) {
        if (other == com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasRepeatCount()) {
          setRepeatCount(other.getRepeatCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.spotify.playlist4.proto.Playlist4Issues.ClientIssue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.spotify.playlist4.proto.Playlist4Issues.ClientIssue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.spotify.proto.ClientIssue.Level level = 1;
      private com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level level_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level.LEVEL_UNKNOWN;
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
       */
      public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level getLevel() {
        return level_;
      }
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
       */
      public Builder setLevel(com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Level level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Level.LEVEL_UNKNOWN;
        onChanged();
        return this;
      }

      // optional .com.spotify.proto.ClientIssue.Code code = 2;
      private com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code.CODE_UNKNOWN;
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
       */
      public com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code getCode() {
        return code_;
      }
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
       */
      public Builder setCode(com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.spotify.proto.ClientIssue.Code code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientIssue.Code.CODE_UNKNOWN;
        onChanged();
        return this;
      }

      // optional int32 repeatCount = 3;
      private int repeatCount_ ;
      /**
       * <code>optional int32 repeatCount = 3;</code>
       */
      public boolean hasRepeatCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 repeatCount = 3;</code>
       */
      public int getRepeatCount() {
        return repeatCount_;
      }
      /**
       * <code>optional int32 repeatCount = 3;</code>
       */
      public Builder setRepeatCount(int value) {
        bitField0_ |= 0x00000004;
        repeatCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 repeatCount = 3;</code>
       */
      public Builder clearRepeatCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        repeatCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.spotify.proto.ClientIssue)
    }

    static {
      defaultInstance = new ClientIssue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.spotify.proto.ClientIssue)
  }

  public interface ClientResolveActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.spotify.proto.ClientResolveAction.Code code = 1;
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
     */
    com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code getCode();

    // optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
     */
    boolean hasInitiator();
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
     */
    com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator getInitiator();
  }
  /**
   * Protobuf type {@code com.spotify.proto.ClientResolveAction}
   */
  public static final class ClientResolveAction extends
      com.google.protobuf.GeneratedMessage
      implements ClientResolveActionOrBuilder {
    // Use ClientResolveAction.newBuilder() to construct.
    private ClientResolveAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientResolveAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientResolveAction defaultInstance;
    public static ClientResolveAction getDefaultInstance() {
      return defaultInstance;
    }

    public ClientResolveAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientResolveAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code value = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator value = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                initiator_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientResolveAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientResolveAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.class, com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientResolveAction> PARSER =
        new com.google.protobuf.AbstractParser<ClientResolveAction>() {
      public ClientResolveAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientResolveAction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientResolveAction> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.spotify.proto.ClientResolveAction.Code}
     */
    public enum Code
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CODE_UNKNOWN = 0;</code>
       */
      CODE_UNKNOWN(0, 0),
      /**
       * <code>CODE_NO_ACTION = 1;</code>
       */
      CODE_NO_ACTION(1, 1),
      /**
       * <code>CODE_RETRY = 2;</code>
       */
      CODE_RETRY(2, 2),
      /**
       * <code>CODE_RELOAD = 3;</code>
       */
      CODE_RELOAD(3, 3),
      /**
       * <code>CODE_DISCARD_LOCAL_CHANGES = 4;</code>
       */
      CODE_DISCARD_LOCAL_CHANGES(4, 4),
      /**
       * <code>CODE_SEND_DUMP = 5;</code>
       */
      CODE_SEND_DUMP(5, 5),
      /**
       * <code>CODE_DISPLAY_ERROR_MESSAGE = 6;</code>
       */
      CODE_DISPLAY_ERROR_MESSAGE(6, 6),
      ;

      /**
       * <code>CODE_UNKNOWN = 0;</code>
       */
      public static final int CODE_UNKNOWN_VALUE = 0;
      /**
       * <code>CODE_NO_ACTION = 1;</code>
       */
      public static final int CODE_NO_ACTION_VALUE = 1;
      /**
       * <code>CODE_RETRY = 2;</code>
       */
      public static final int CODE_RETRY_VALUE = 2;
      /**
       * <code>CODE_RELOAD = 3;</code>
       */
      public static final int CODE_RELOAD_VALUE = 3;
      /**
       * <code>CODE_DISCARD_LOCAL_CHANGES = 4;</code>
       */
      public static final int CODE_DISCARD_LOCAL_CHANGES_VALUE = 4;
      /**
       * <code>CODE_SEND_DUMP = 5;</code>
       */
      public static final int CODE_SEND_DUMP_VALUE = 5;
      /**
       * <code>CODE_DISPLAY_ERROR_MESSAGE = 6;</code>
       */
      public static final int CODE_DISPLAY_ERROR_MESSAGE_VALUE = 6;


      public final int getNumber() { return value; }

      public static Code valueOf(int value) {
        switch (value) {
          case 0: return CODE_UNKNOWN;
          case 1: return CODE_NO_ACTION;
          case 2: return CODE_RETRY;
          case 3: return CODE_RELOAD;
          case 4: return CODE_DISCARD_LOCAL_CHANGES;
          case 5: return CODE_SEND_DUMP;
          case 6: return CODE_DISPLAY_ERROR_MESSAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Code>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Code>() {
              public Code findValueByNumber(int number) {
                return Code.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.getDescriptor().getEnumTypes().get(0);
      }

      private static final Code[] VALUES = values();

      public static Code valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Code(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.spotify.proto.ClientResolveAction.Code)
    }

    /**
     * Protobuf enum {@code com.spotify.proto.ClientResolveAction.Initiator}
     */
    public enum Initiator
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INITIATOR_UNKNOWN = 0;</code>
       */
      INITIATOR_UNKNOWN(0, 0),
      /**
       * <code>INITIATOR_SERVER = 1;</code>
       */
      INITIATOR_SERVER(1, 1),
      /**
       * <code>INITIATOR_CLIENT = 2;</code>
       */
      INITIATOR_CLIENT(2, 2),
      ;

      /**
       * <code>INITIATOR_UNKNOWN = 0;</code>
       */
      public static final int INITIATOR_UNKNOWN_VALUE = 0;
      /**
       * <code>INITIATOR_SERVER = 1;</code>
       */
      public static final int INITIATOR_SERVER_VALUE = 1;
      /**
       * <code>INITIATOR_CLIENT = 2;</code>
       */
      public static final int INITIATOR_CLIENT_VALUE = 2;


      public final int getNumber() { return value; }

      public static Initiator valueOf(int value) {
        switch (value) {
          case 0: return INITIATOR_UNKNOWN;
          case 1: return INITIATOR_SERVER;
          case 2: return INITIATOR_CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Initiator>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Initiator>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Initiator>() {
              public Initiator findValueByNumber(int number) {
                return Initiator.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.getDescriptor().getEnumTypes().get(1);
      }

      private static final Initiator[] VALUES = values();

      public static Initiator valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Initiator(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.spotify.proto.ClientResolveAction.Initiator)
    }

    private int bitField0_;
    // optional .com.spotify.proto.ClientResolveAction.Code code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code code_;
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
     */
    public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code getCode() {
      return code_;
    }

    // optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;
    public static final int INITIATOR_FIELD_NUMBER = 2;
    private com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator initiator_;
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
     */
    public boolean hasInitiator() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
     */
    public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator getInitiator() {
      return initiator_;
    }

    private void initFields() {
      code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code.CODE_UNKNOWN;
      initiator_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator.INITIATOR_UNKNOWN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, initiator_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, initiator_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.spotify.proto.ClientResolveAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.spotify.playlist4.proto.Playlist4Issues.ClientResolveActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientResolveAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientResolveAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.class, com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Builder.class);
      }

      // Construct using com.com.spotify.proto.Playlist4Issues.ClientResolveAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code.CODE_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        initiator_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator.INITIATOR_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spotify.playlist4.proto.Playlist4Issues.internal_static_spotify_playlist4_proto_ClientResolveAction_descriptor;
      }

      public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction getDefaultInstanceForType() {
        return com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.getDefaultInstance();
      }

      public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction build() {
        com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction buildPartial() {
        com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction result = new com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.initiator_ = initiator_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction) {
          return mergeFrom((com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction other) {
        if (other == com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasInitiator()) {
          setInitiator(other.getInitiator());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.spotify.proto.ClientResolveAction.Code code = 1;
      private com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code.CODE_UNKNOWN;
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
       */
      public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code getCode() {
        return code_;
      }
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
       */
      public Builder setCode(com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Code code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Code.CODE_UNKNOWN;
        onChanged();
        return this;
      }

      // optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;
      private com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator initiator_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator.INITIATOR_UNKNOWN;
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
       */
      public boolean hasInitiator() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
       */
      public com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator getInitiator() {
        return initiator_;
      }
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
       */
      public Builder setInitiator(com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        initiator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.spotify.proto.ClientResolveAction.Initiator initiator = 2;</code>
       */
      public Builder clearInitiator() {
        bitField0_ = (bitField0_ & ~0x00000002);
        initiator_ = com.spotify.playlist4.proto.Playlist4Issues.ClientResolveAction.Initiator.INITIATOR_UNKNOWN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.spotify.proto.ClientResolveAction)
    }

    static {
      defaultInstance = new ClientResolveAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.spotify.proto.ClientResolveAction)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spotify_playlist4_proto_ClientIssue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spotify_playlist4_proto_ClientIssue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spotify_playlist4_proto_ClientResolveAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spotify_playlist4_proto_ClientResolveAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025playlist4issues.proto\022\027spotify.playlis" +
      "t4.proto\"\252\003\n\013ClientIssue\0229\n\005level\030\001 \001(\0162" +
      "*.com.spotify.proto.ClientIssue.Le" +
      "vel\0227\n\004code\030\002 \001(\0162).spotify.playlist4.pr" +
      "oto.ClientIssue.Code\022\023\n\013repeatCount\030\003 \001(" +
      "\005\"q\n\005Level\022\021\n\rLEVEL_UNKNOWN\020\000\022\017\n\013LEVEL_D" +
      "EBUG\020\001\022\016\n\nLEVEL_INFO\020\002\022\020\n\014LEVEL_NOTICE\020\003" +
      "\022\021\n\rLEVEL_WARNING\020\004\022\017\n\013LEVEL_ERROR\020\005\"\236\001\n" +
      "\004Code\022\020\n\014CODE_UNKNOWN\020\000\022\034\n\030CODE_INDEX_OU" +
      "T_OF_BOUNDS\020\001\022\031\n\025CODE_VERSION_MISMATCH\020\002",
      "\022\026\n\022CODE_CACHED_CHANGE\020\003\022\027\n\023CODE_OFFLINE" +
      "_CHANGE\020\004\022\032\n\026CODE_CONCURRENT_CHANGE\020\005\"\225\003" +
      "\n\023ClientResolveAction\022?\n\004code\030\001 \001(\01621.sp" +
      "otify.playlist4.proto.ClientResolveActio" +
      "n.Code\022I\n\tinitiator\030\002 \001(\01626.spotify.play" +
      "list4.proto.ClientResolveAction.Initiato" +
      "r\"\241\001\n\004Code\022\020\n\014CODE_UNKNOWN\020\000\022\022\n\016CODE_NO_" +
      "ACTION\020\001\022\016\n\nCODE_RETRY\020\002\022\017\n\013CODE_RELOAD\020" +
      "\003\022\036\n\032CODE_DISCARD_LOCAL_CHANGES\020\004\022\022\n\016COD" +
      "E_SEND_DUMP\020\005\022\036\n\032CODE_DISPLAY_ERROR_MESS",
      "AGE\020\006\"N\n\tInitiator\022\025\n\021INITIATOR_UNKNOWN\020" +
      "\000\022\024\n\020INITIATOR_SERVER\020\001\022\024\n\020INITIATOR_CLI" +
      "ENT\020\002B\037\n\033com.spotify.playlist4.protoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_spotify_playlist4_proto_ClientIssue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_spotify_playlist4_proto_ClientIssue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spotify_playlist4_proto_ClientIssue_descriptor,
              new java.lang.String[] { "Level", "Code", "RepeatCount", });
          internal_static_spotify_playlist4_proto_ClientResolveAction_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_spotify_playlist4_proto_ClientResolveAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spotify_playlist4_proto_ClientResolveAction_descriptor,
              new java.lang.String[] { "Code", "Initiator", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
